INSERT INTO PLAYER (NAME) VALUES
	 ('IbaiLlanos'),
	 ('Alexelcapo'),
	 ('ANONYMOUS');

INSERT INTO CRAPSROLL
(ID_CRAPSROLL, ID_PLAYER, CRAP_ONE, CRAP_TWO, ROLL_RESULT)
VALUES(1, 1, 5, 2, 7);
INSERT INTO CRAPSROLL
(ID_CRAPSROLL, ID_PLAYER, CRAP_ONE, CRAP_TWO, ROLL_RESULT)
VALUES(2, 1, 5, 5, 10);
INSERT INTO CRAPSROLL
(ID_CRAPSROLL, ID_PLAYER, CRAP_ONE, CRAP_TWO, ROLL_RESULT)
VALUES(3, 1, 6, 6, 12);

INSERT INTO CRAPSROLL
(ID_CRAPSROLL, ID_PLAYER, CRAP_ONE, CRAP_TWO, ROLL_RESULT)
VALUES(4, 2, 5, 2, 7);
INSERT INTO CRAPSROLL
(ID_CRAPSROLL, ID_PLAYER, CRAP_ONE, CRAP_TWO, ROLL_RESULT)
VALUES(5, 2, 5, 3, 8);

INSERT INTO CRAPSROLL
(ID_CRAPSROLL, ID_PLAYER, CRAP_ONE, CRAP_TWO, ROLL_RESULT)
VALUES(6, 3, 5, 2, 7);
INSERT INTO CRAPSROLL
(ID_CRAPSROLL, ID_PLAYER, CRAP_ONE, CRAP_TWO, ROLL_RESULT)
VALUES(7, 3, 2, 5, 7);

INSERT INTO GAME
(ID_GAME, ID_PLAYER, ID_CRAPSROLL, GAME_RESULT)
VALUES(1, 1, 1, true);
INSERT INTO GAME
(ID_GAME, ID_PLAYER, ID_CRAPSROLL, GAME_RESULT)
VALUES(2, 1, 2, false);
INSERT INTO GAME
(ID_GAME, ID_PLAYER, ID_CRAPSROLL, GAME_RESULT)
VALUES(3, 1, 3, false);

INSERT INTO GAME
(ID_GAME, ID_PLAYER, ID_CRAPSROLL, GAME_RESULT)
VALUES(1, 2, 4, true);
INSERT INTO GAME
(ID_GAME, ID_PLAYER, ID_CRAPSROLL, GAME_RESULT)
VALUES(2, 2, 5, false);

INSERT INTO GAME
(ID_GAME, ID_PLAYER, ID_CRAPSROLL, GAME_RESULT)
VALUES(1, 3, 6, true);
INSERT INTO GAME
(ID_GAME, ID_PLAYER, ID_CRAPSROLL, GAME_RESULT)
VALUES(2, 3, 7, true);



