DROP TABLE IF EXISTS PLAYER;
DROP TABLE IF EXISTS CRAPSROLL;
DROP TABLE IF EXISTS GAME;

CREATE TABLE PLAYER (
	ID_PLAYER INTEGER NOT NULL AUTO_INCREMENT,
	ENTRY_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	NAME VARCHAR(250) NOT NULL,
	CONSTRAINT PLAYER_PK PRIMARY KEY (ID_PLAYER)
);

CREATE TABLE CRAPSROLL (
	ID_CRAPSROLL INTEGER NOT NULL AUTO_INCREMENT,
	ID_PLAYER INTEGER NOT NULL,
	CRAP_ONE SMALLINT NOT NULL,
	CRAP_TWO SMALLINT NOT NULL,
	ROLL_RESULT SMALLINT NOT NULL,
	CONSTRAINT CRAPSROLL_PK PRIMARY KEY (ID_CRAPSROLL),
	CONSTRAINT CRAPSROLL_FK_ FOREIGN KEY (ID_PLAYER) REFERENCES PLAYER(ID_PLAYER) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE GAME (
	ID_GAME INTEGER NOT NULL AUTO_INCREMENT,
	ID_PLAYER INTEGER NOT NULL,
	ID_CRAPSROLL INTEGER NULL,
	GAME_RESULT BOOLEAN NOT NULL,
	CONSTRAINT GAME_PK PRIMARY KEY (ID_GAME,ID_PLAYER),
	CONSTRAINT GAME_FK_PLAYER FOREIGN KEY (ID_PLAYER) REFERENCES PLAYER(ID_PLAYER) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT GAME_FK_CRAPSROLL FOREIGN KEY (ID_CRAPSROLL) REFERENCES CRAPSROLL(ID_CRAPSROLL) ON DELETE SET NULL ON UPDATE CASCADE
);
